CREATE TABLE clientes (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    cpf VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    endereco VARCHAR(50) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP
    );
    
CREATE TABLE vendedores (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    cpf VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    endereco VARCHAR(50) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP
    );
    
CREATE TABLE produtos (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    produto VARCHAR(50) NOT NULL,
    unidade_venda VARCHAR(20) NOT NULL,
    preco_unitario FLOAT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP
    );
    
CREATE TABLE pagamentos (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tipo VARCHAR(50) NOT NULL,
    condicao VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP
    );
   
CREATE TABLE vendas (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    data_venda DATE NOT NULL,
    cliente BIGINT NOT NULL,
    vendedor BIGINT NOT NULL,
    produto BIGINT NOT NULL,
    pagamento BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente) REFERENCES clientes(id),
    FOREIGN KEY (vendedor) REFERENCES vendedores(id),
    FOREIGN KEY (produto) REFERENCES produtos(id),
    FOREIGN KEY (pagamento) REFERENCES pagamentos(id)
    );